### ISSUE TITLE
Yellow highlight doesn't appear when it should

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#133] opened 2015-06-16 19:36 UTC
@bryo5363 reported in #88:

> I noticed that when clicking on the blue figure's hand, the yellow ring around the knot on the rope will illuminate. However, when clicking on the red figure's hand, the yellow ring will not appear.

**Comment by samreid** [comment] 2015-07-29 12:32
I'm going to unassign the issue for now--it will be addressed when I work on all Forces and Motion: Basics issues for the upcoming S2015R redeploy.

**Comment by jessegreenberg** [comment] 2016-02-11 01:16
I see the following in PullerNode.js

```js
          //Hack around the puller position, which seems to be broken for blue pullers for unknown reasons
          if ( knot && puller.type === 'blue' ) {
            puller.position = puller.position.plusXY(
              puller.size === 'small' ? -50 :
              puller.size === 'medium' ? -30 :
              -40,
              puller.size === 'small' ? -30 :
              puller.size === 'medium' ? -90 :
              -140 );
          }
```

It looks like a similar correction is needed for red pullers, but to a lesser extent.  However, maybe something in ```updateImage()``` could be causing this.

**Comment by jessegreenberg** [comment] 2016-02-11 22:40
It looks like this issue is caused by the order of operations in the puller node simple drag handler start function.

The PullerNode is disconnected first and then the image is updated, which means that the updateImage function assumes that the puller is never knotted on click.  This means that 

```js
this.setTranslation( puller.position )
``` 

is always called instead of 
```js
this.setTranslation( puller.knot.x + pullingOffset + blueOffset, puller.knot.y - this.height + 90 );
```

to correct for the fact that the translation is relative to the image origin.

**Comment by jessegreenberg** [comment] 2016-02-11 22:43
It looks like code to translate the image in ```updateImage``` can now be removed now that focus highlights are handled in FocusOverlay.js in a separate display.

Because of this, we can simplify the simpleDragHandler start function and remove the 'hack' above.
```js
        start: function() {

          // update the image
          pullerNode.updateImage( puller, model );
          pullerNode.updateLocation( puller, model );

          puller.disconnect();
          puller.dragging = true;
          pullerNode.moveToFront();
          puller.trigger( 'dragged' );

        },
```

**Comment by jessegreenberg** [comment] 2016-02-11 22:54
Ah, looks like I misread the comment.  The translation code in updateImage *is* necessary to correctly translate the puller image after scales change.

**Comment by jessegreenberg** [comment] 2016-02-12 21:45
Node translations fixed.  However, yellow highlights do not appear until drag handler translation starts.

**Comment by jessegreenberg** [comment] 2016-02-12 21:52
Knot highlight visibility updates when puller position changes.  This does not happen in the drag handler ```start``` function since the function sets the translation directly.

**Comment by jessegreenberg** [comment] 2016-02-12 22:28
Fixed in commits above, closing.

**Closed by jessegreenberg** 2016-02-12 22:28 UTC
Labels: task:S2015R
