### ISSUE TITLE
Sim performance is severely affected when clicking on "pushed" objects

### ISSUE THREAD

**Issue by bryo5363** [phetsims/forces-and-motion-basics#105] opened 2014-11-18 18:43 UTC
Test device: MacBook Pro

Operating System: 10.8.5

Browser: Chrome 37.0.2062.120

Problem description: When clicking objects that the pushing man exerts a force on, the performance of the simulation is affected

Steps to reproduce:
-open sim
-go to acceleration
-switch the box to the man and the water bucket
-while the pushing man exerts a force on the system, click the man or the water bucket repeatedly.
-Notice the simulation will slow down 
Severity:

Screenshots:
![fmb](https://cloud.githubusercontent.com/assets/7717368/5093732/1bc2d3b8-6f18-11e4-9c4b-2f856936e382.gif)

Troubleshooting information (do not edit):
Name: Forces and Motion: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.0-rc.1/forces-and-motion-basics_en.html
Version: 1.1.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36
Language: en-US
Window: 1050x595
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jessegreenberg** [comment] 2016-02-12 23:02
Was able to reproduce on Windows FF and Chrome, most noticeable in FF.

**Comment by jessegreenberg** [comment] 2016-02-12 23:13
Now I am having a very hard time reproducing, even in Firefox.  I will need to test and profile with a PHET testing device.

**Comment by jessegreenberg** [comment] 2016-02-18 00:06
Very easy to reproduce on the published version ( http://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html ), but I cannot reproduce locally.

**Comment by jessegreenberg** [comment] 2016-02-25 00:36
This issue was reported on a MacBook Pro, I will try to reproduce with a testing device tomorrow.

**Comment by jessegreenberg** [comment] 2016-02-26 01:04
Just tested this on phet test devices Jordan and Dirac, both with Chrome and Firefox.  Also tried to reproduce on my Windows 10 machine.  I could not reproduce this issue.  Closing.

**Closed by jessegreenberg** 2016-02-26 01:04 UTC
Labels: task:S2015R, type:performance
