### ISSUE TITLE
User request - add tweakers to Friction slider

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#199] opened 2016-09-12 16:23 UTC
Problem description:
Friction slider unable to select 50, 100,150N exactly.
( or force slider not granular)

Steps to reproduce:

Using the friction screen I wanted to setup a situation where the student first applied say 150N with the friction 100N  then dropped the force once it was moving to 100N  and  observe the constant velocity.  The default setup for friction gives 94N once moving.  I tried adjusting the friction slider ( as I can’t change the force applied in a granular manner)  and it will either choose 99 or 101N not 100N.  This means a zero resultant force but moving with constant velocity case cannot be generated.

Whilst I can use the force slider to select 94N its sensitive and I need to keep it clicked or it will release the force, which makes it harder to observe.

Either:  Friction slider be adjusted to allow 100N etc. selection
OR:  allow force to be entered as text entry

**Comment by oliver-phet** [comment] 2016-09-12 16:23
Could be related to https://github.com/phetsims/forces-and-motion-basics/issues/197

**Comment by jessegreenberg** [comment] 2016-09-12 16:47
@oliver-phet did the user happen to provide platform details?  I would expect this to be an issue for a smaller screens.

**Comment by oliver-phet** [comment] 2016-09-12 16:51
"Toshiba Laptop" 
Window: 1366x589

I just tested on my mac and it was fairly difficult to get an exact number.

**Comment by jessegreenberg** [comment] 2016-09-12 16:52
I just tested latest deployed version - I cannot reproduce on my Windows 10 laptop, or iPad3 (diSessa) in landscape mode, but I can reproduce with the iPad3 in portrait mode since the slider is smaller.

**Comment by ariel-phet** [comment] 2016-09-12 16:53
I do not think we would make this change to the friction slider. Tweakers are meant to be fine grained adjustments, and the friction slider is qualitative. In fact the friction slider is really adjusting the "Coefficient of friction" not the frictional force itself (the two are of course related). But for for instance, with "friction" set to the same slider position, adding additional mass will increase the maximum frictional force.

Being able to "dial in" the applied force to a specific value is something we could consider

**Comment by oliver-phet** [comment] 2016-09-12 16:56
This is the second instance of a teacher requesting fine-grained adjustment of the friction slider (in order to match the Applied Force) within a week.

**Comment by ariel-phet** [comment] 2016-09-12 17:12
@oliver-phet understood - but the right solution would be to allow finer grained adjust of the applied force (right now the tweakers allow a 50 newton jump)

**Comment by ariel-phet** [comment] 2016-09-12 17:21
@jessegreenberg since you are making some other changes, lets also try this...

Can you put in another set of tweakers like the mockup below (with generous touch areas) that allow a 1 Newton increment of the applied force, and have the same action as the large tweakers, in that they continue to apply the force (unlike the slider that snaps back to zero)

![applied force](https://cloud.githubusercontent.com/assets/4051174/18445491/0e68573c-78db-11e6-9c8c-4130b00ec08a.PNG)

**Comment by oliver-phet** [comment] 2016-09-12 17:40
Just my opinion - if a teacher is asking a class of students to match the friction and applied forces, it would require students setting some arbitrary friction value, then matching with the applied force tweakers? Seems like it would be difficult for students to get consistent results.

**Comment by ariel-phet** [comment] 2016-09-12 17:50
@oliver-phet tweakers would only makes sense if we had a readout for the "coefficient of friction" - but we decided long ago that in the basics version, we were not going to get into exposing the coefficient. When we eventually port the "full" forces and motion, we will do that, but for the basics version it definitely makes sense to keep this slider qualitative. 

It actually send a confusing message if we put tweakers on the "Friction" slider. Here is why:

- Suppose in a certain situation the tweaker allows you to change the frictional force by an increment of "1 Newton" ...since you are really changing the coefficient of friction, if you added more mass (thus changing the normal force) the tweaker now should still increment the same amount in terms of coefficient of friction, but you would see the frictional force change by more of an increment (say 2 Newtons if you had doubled the mass). That would be confusing.

**Comment by jessegreenberg** [comment] 2016-09-12 23:43
@ariel-phet here is a version with the buttons like the mockup in https://github.com/phetsims/forces-and-motion-basics/issues/199#issuecomment-246422784.
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.2-dev.1/forces-and-motion-basics_en.html

@phet-steele and @arouinfar suggested and preferred a double arrow button rather than a scaled down button, so that it looks like this:
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.2-dev.2/forces-and-motion-basics_en.html

The double arrows can be spaced and adjusted, but what do you think @ariel-phet?

**Comment by ariel-phet** [comment] 2016-09-13 00:16
@jessegreenberg @arouinfar @phet-steele 

There is a bit of cognitive dissonance with the double-arrows (each arrow is small) and then the single arrow is large, so I think it is not immediately obvious which button will make the big jump.

I am fine with the double arrow design, but then the "1 Newton" tweaker should have a single arrow that is small (even if the button remains large).

**Comment by arouinfar** [comment] 2016-09-13 00:45
> There is a bit of cognitive dissonance with the double-arrows (each arrow is small) and then the single arrow is large, so I think it is not immediately obvious which button will make the big jump.

While the double arrow design isn't perfect, I found it less confusing than differently sized buttons.

> then the "1 Newton" tweaker should have a single arrow that is small (even if the button remains large)

This seems reasonable to me @ariel-phet.

**Comment by arouinfar** [comment] 2016-09-13 00:46
Self-assigning to update the teacher tips once a new version is released.

**Comment by jessegreenberg** [comment] 2016-09-13 17:35
![capture](https://cloud.githubusercontent.com/assets/6396244/18484461/c4415e3a-79a5-11e6-9e07-fda1e620401b.PNG)

@ariel-phet @arouinfar @phet-steele From the above comments, maybe something like this?  It is kind of 'pixel-polishing' at this point, maybe it would be fastest to get it just right over a quick video call.

**Comment by ariel-phet** [comment] 2016-09-13 18:34
@jessegreenberg and I discussed and made some tweaks, he will post another dev version for review.

**Comment by jessegreenberg** [comment] 2016-09-14 01:50
@ariel-phet @arouinfar @phet-steele here is the new dev version for review:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.2-dev.3/forces-and-motion-basics_en.html

If all looks good, we are ready for maintenance release RC.

**Comment by ariel-phet** [comment] 2016-09-14 02:06
Looks great to me

**Comment by arouinfar** [comment] 2016-09-14 02:52
:+1:

**Comment by jessegreenberg** [comment] 2016-09-14 18:19
Excellent, also assigning to @oliver-phet in case he would like to respond to original reporter once redeploy complete.

**Comment by oliver-phet** [comment] 2016-09-14 18:48
ETA of redeploy? ETR?

**Comment by arouinfar** [comment] 2016-09-14 19:33
Updated Teacher Tips are ready to go. I'll upload them after the redeploy.

**Comment by jessegreenberg** [comment] 2016-09-14 19:36
ETR Most likely tomorrow or friday, just need to successfully pass the RC test.

**Comment by phet-steele** [comment] 2016-09-14 21:25
> ETR Most likely tomorrow or friday, just need to successfully pass the RC test.

Won't be some time. New release testing (which we have lots of) take precedence over redeploys/maintenance deploys, so this is low priority.

**Comment by jessegreenberg** [comment] 2016-09-14 21:26
Thanks for clarifying @phet-steele, didn't mean to presume.

**Comment by jessegreenberg** [comment] 2016-09-14 23:18
From https://github.com/phetsims/sun/issues/265, @pixelzoom suggested another way to style the arrows:
>...it looks very odd that the double arrows have different dimensions than the single arrows. A more conventional (?) look would be something like the screenshot below...
![4c1aecfe-7a8c-11e6-936f-0069e06f5378](https://cloud.githubusercontent.com/assets/6396244/18533147/247d42d4-7a9e-11e6-9ac2-332a0ae1cda5.png)

I agree this does look a bit nicer.  As a general double (or more) arrow button, it might be nicer to have this kind style used throughout sims.

@pixelzoom also mentioned
> In FAMB, should the double arrow buttons be swapped with the single arrow buttons? It seems like the smaller increment (single arrow) buttons should be closest to the value.

To me, it makes more intuitive sense for the gross adjustment to be on the inside and the fine adjustment to be on the outside.

@ariel-phet @arouinfar @phet-steele any thoughts about these recommendations?

**Comment by ariel-phet** [comment] 2016-09-15 00:02
I could go for that style, it clearly says "more" than the single arrow to me.

Agree with @jessegreenberg I also feel like it makes more sense to have the gross adjustment on the inside. I have a bit of a tough time articulating why, but perhaps that feeling of descending  on each side ( _-- Value -- _ ) so little adjust, big adjust, value, big adjust, little adjust. Feels more intuitive and nice symmetry to me. When I used it in the sim, it felt very natural.

**Comment by arouinfar** [comment] 2016-09-15 00:05
@jessegreenberg I have a slight preference for the new double arrow, but I could go either way.

> I also feel like it makes more sense to have the gross adjustment on the inside.

Ditto.

**Comment by jessegreenberg** [comment] 2016-09-30 20:34
@ariel-phet and @arouinfar here is the version with changes to the arrow styling.  Look good before updating the RC test task?

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.2/forces-and-motion-basics_en.html

**Comment by ariel-phet** [comment] 2016-09-30 20:51
@jessegreenberg could we pull the double triangles apart just a bit further such as in this image:

http://findicons.com/files/icons/49/button/300/button_fast_forward.png

**Comment by jessegreenberg** [comment] 2016-09-30 21:00
Like so?
![test2](https://cloud.githubusercontent.com/assets/6396244/19006751/750b757c-871e-11e6-84a1-c0715554c21e.PNG)

**Comment by arouinfar** [comment] 2016-09-30 23:26
@jessegreenberg your updated screenshot looks pretty good to me.

**Comment by ariel-phet** [comment] 2016-10-04 17:48
Yes Looks good to me!

**Comment by ariel-phet** [comment] 2016-10-04 17:49
Yes @jessegreenberg looks good to me!

**Comment by arouinfar** [comment] 2016-10-20 16:41
Unassigning myself since the updated Teacher Tips are ready to upload with the redeploy.

**Comment by jessegreenberg** [comment] 2016-11-09 21:39
@arouinfar the sim has been redeployed, do the teacher tips need to be uploaded now?

**Comment by jessegreenberg** [comment] 2016-11-10 16:15
@arouinfar with #209 done can this be closed?

**Comment by arouinfar** [comment] 2016-11-10 17:07
It can indeed @jessegreenberg.

**Closed by arouinfar** 2016-11-10 17:07 UTC
Labels: dev:enhancement
