### ISSUE TITLE
Pixelated "pusher" on motion screens

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#157] opened 2016-02-03 00:14 UTC
@jessegreenberg the pusher on the motion screens is quite pixelated/aliased. Please let me know if this issue can be fixed by mipmapping or such...or do we need new artwork?

If new artwork is required, please assign back to me (I also do not believe we have the original .ai file for the pusher, so it may be good to redraw anyhow to have a proper asset).

**Comment by jessegreenberg** [comment] 2016-02-03 18:02
@ariel-phet we will need new artwork to fix this.  The pixelation is in the artwork, it is not caused by scaling or the browser.

You are right, i could not find the original .ai file in assets.

**Comment by ariel-phet** [comment] 2016-02-03 18:04
Will do

**Comment by jessegreenberg** [comment] 2016-02-03 18:05
However, new artwork would mean creating 17 new images for all of the possible states of the pusher as it pushes on the items.

**Comment by ariel-phet** [comment] 2016-02-03 18:07
@jessegreenberg I actually don't think creating the multiple new images will be much of an issue for our artist once the initial image is created

**Comment by jessegreenberg** [comment] 2016-02-03 18:16
Very cool!  New artwork would look great!

**Comment by ariel-phet** [comment] 2016-02-08 05:25
To be addressed in https://github.com/phetsims/tasks/issues/501

**Comment by ariel-phet** [comment] 2016-02-08 22:38
assigning back to @jessegreenberg to take care of once new artwork has been generated

**Comment by ariel-phet** [comment] 2016-02-23 19:00
@jessegreenberg this artwork is now in drive

https://drive.google.com/drive/folders/0B-YvjkIIcS_aRVFvZ2NDYlZ6Qkk

file "figure32.ai"

**Comment by ariel-phet** [comment] 2016-02-23 19:02
And let me know if you need any help generating the pngs

**Comment by jessegreenberg** [comment] 2016-02-25 00:34
New pusher images added, and they are pretty great!  Here is a dev version to play with the new images:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.5-dev.15/forces-and-motion-basics_en.html

Adding the 'ready for review' tag.

**Comment by jessegreenberg** [comment] 2016-02-25 00:34
Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment] 2016-02-25 01:28
@jessegreenberg These look very good, and working nice and smoothly!

Are the images mipmapped...if not -- is that appropriate to do here? or will that hog performance and such because so many images?

**Comment by jessegreenberg** [comment] 2016-02-25 18:07
@ariel-phet, the images are loaded as mipmaps.  The image quality seemed best this way, so I wanted to see if we could get away with it.  This does increase the memory footprint significantly.  It seems to be working well, but I will test on other devices.  If there are issues, we can investigate other solutions.

**Comment by jessegreenberg** [comment] 2016-03-16 20:09
Indeed, sim does not launch on iPad2, hangs on loading screen.  Removing PusherNode references from MotionScreenView allows sim to launch again.

We can export smaller images from the assets directly, and hopefully maintain decent resolution without mipmaps.

First I will try replacing mipmap with image plugin in PusherNode to make sure this fixes the loading issue.

**Comment by jessegreenberg** [comment] 2016-03-16 23:52
Replaced mipmaps with images, sim loads on iPad2 once more.  Will try exporting smaller images to avoid mipmaps.

**Comment by jessegreenberg** [comment] 2016-03-17 01:03
Pusher images pre scaled with Illustrator, images look crisp in simulation, sim runs on iPad. Closing.

**Closed by jessegreenberg** 2016-03-17 01:03 UTC
Labels: dev:enhancement, task:S2015R
