### ISSUE TITLE
Recording on Win 10 Firefox not saved with back arrow

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#263] opened 2018-09-14 15:07 UTC
For https://github.com/phetsims/QA/issues/187

While working on the recording part of step 3 of the above issue, firefox did not seem to save the data when the back button was used.

From instructions:
> When you are done recording a session, try press the back button or exit out of the tab. You will be prompted if you want to leave the page. DON'T LEAVE (very important)!! Instead press "cancel". At this point a dialog will pop up that says "There is data not saved!". Wait for the progress bar to fully complete, and then you can safely leave the page. NOTE: if you try to leave the page while the progress bar is still "saving", nothing will stop you, but some data will be lost, so please stay until the progress bar reaches 100%, and the message changes to "Data Saved!".

When exiting out of the tab the wrapper performed as expected, but using the back arrow did not produce the dialog described.

**Comment by KatieWoe** [comment] 2018-09-14 18:28
Update upon downloading recordings and playing back.  This recording does seem to have made it with no problem.  The dialog did not appear and there is no way to judge ahead of time it data was saved, but the recording was saved in this instance.

**Comment by zepumph** [comment] 2018-09-14 23:35
Weirdly similar but different from https://github.com/phetsims/phet-io-wrappers/issues/15

@samreid I wonder if firefox handles the 'unload' event differently. Here is the code that should add the dialog:

```js
                window.addEventListener( 'unload', function() {
                  console.log( 'Stopping Metacog' );
                  Metacog.stop();
                } );

```

Firefox really likes giving users control, so maybe there is a user setting where you have to opt in to a dialog appearing when you hit the back button.

@KatieWoe could you run another test for this issue, in which, while recording on the same system as noted above, you record a lengthy session (at least 5 minutes) with lots of events (perhaps let the box slide quickly forever on friction less ground), then press the back button and see if the recorded session is shorter than you would expect? (I know you are leaving soon, don't worry about it for today)

**Comment by KatieWoe** [comment] 2018-09-15 00:03
@zepumph Just attempted to make a recording of 5 minutes on the same system.  Can't tell if it saved.  Will find out Monday.

**Comment by KatieWoe** [comment] 2018-09-17 14:49
@zepumph just checked the recording.  I recorded for 5 minutes.  The time on the recording says 4:58 and it doesn't look like anything is missing from the recording from what I can tell.

**Comment by zepumph** [comment] 2018-09-17 16:32
That's great news thanks. It is possible that this is in part because you have a good connection. Events that you are emitting are able to be sent to metacog with relative speed, such that the sending queue is relatively short. 

Would it be possible to try to throttle your internet and then record again and see if the playback log is missing anything (note that if there is an error in the log, the playback wrapper will note it as such with an asterisk).

You can adjust your speed in a dropdown in the network tab:
![image](https://user-images.githubusercontent.com/6856943/45636312-d7c71300-ba53-11e8-94ad-82b7002f7dec.png)

Also https://blog.nightly.mozilla.org/2016/11/07/simulate-slow-connections-with-the-network-throttling-tool/ may be helpful.

If after 5 minutes of emitting many events on a very slow connection, perhaps we will be more likely to trigger an error. If this doesn't break a session, then we may think tagging this issue as a won't fix.

**Comment by KatieWoe** [comment] 2018-09-17 16:53
Interesting discovery while doing this test.  I found that if you hit the back arrow once, the screen goes blank.  Hitting the arrow a second time when the speed is throttled did bring up the warning message.  It didn't before, which makes me think it finished before I hit it a second time.  Not sure why it is two back arrows here, and not one.  Still going to test the recording itself, but in the meantime this might help. @zepumph
![saving](https://user-images.githubusercontent.com/41024075/45637495-dd2e5880-ba67-11e8-8537-a64a6153139a.PNG)

**Comment by zepumph** [comment] 2018-09-17 17:04
It sounds like we can safely say that this is a duplicate of https://github.com/phetsims/phet-io-wrappers/issues/15 then, but displaying symptoms with a fast internet connection.

**Comment by KatieWoe** [comment] 2018-09-17 18:06
@zepumph just looked at the recording and it looks ok.

**Comment by KatieWoe** [comment] 2018-09-20 15:16
Looks like this appears in https://github.com/phetsims/QA/issues/190 as well.  Linking here.

**Comment by samreid** [comment] 2023-03-25 15:12
We no longer support Metacog as a data storage/retrieval service, closing.

**Closed by samreid** 2023-03-25 15:12 UTC
Labels: type:bug, phet-io:record-and-playback
