### ISSUE TITLE
Force Man appears and slides along the ground with an object

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#106] opened 2014-11-18 19:02 UTC
Seen on 1.1.0-rc.1 in Windows 8.1 (FF, Chrome, IE11). The force man will appear next to an object and continue to slide along the ground with the object.
Steps:
1. Go to either screen with friction as an option.
2. Slide friction to zero, all the way to the left.
3. Push (in either direction) until you can't push anymore and the object is moving at max speed.
4. Once the now laying down force man is left behind and goes off screen, hang tight and don't do anything in the sim.
5. Hang tight some more.
6. Once 5 or 6 seconds have passed, increase the friction on the object, by any amount.
Eventually the force man should appear and move along the ground. If he doesn't, try the steps again and wait longer during step 5. If not enough time passes before friction is increased the man does not seem to ever appear. Note that the man appears in tandem with being able to apply force back in the original direction (ex. if I push to the right up to max speed, the right side of the force slider gets grayed out because I can no longer apply force. In the video below, notice that even after friction is introduced to the object the right hand side of the slider remains grayed out for a good amount of time.)

The video:
https://drive.google.com/file/d/0B3HJopSo_QqLMVI1U3Izb0lUQXc/view?usp=sharing

Troubleshooting information:
Name: Forces and Motion: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.0-rc.1/forces-and-motion-basics_en.html
Version: 1.1.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jessegreenberg** [comment] 2016-02-16 00:01
These issues are caused by the optimization: 

```js
     var x = layoutWidth / 2 + (model.pusherPosition - model.position) * MotionConstants.POSITION_SCALE;
      //To save processor time, don't update the image if it is too far offscreen
      if ( x > -2000 && x < 2000 ) {
        visibleNode.translate( x - visibleNode.getCenterX(), pusherY - visibleNode.y, true );
      }
```

**Comment by jessegreenberg** [comment] 2016-02-16 01:13
Fixed in commit above, optimization is only applied if pusher model position changes. If forces change or the pusher falls down, the pusher node is still translated.

However, there is still a delay in the activation of the Force slider, as described by @phet-steele in https://github.com/phetsims/forces-and-motion-basics/issues/106#issuecomment-63531670.  That is a separate issue, will make another and close this one.

**Closed by jessegreenberg** 2016-02-16 01:13 UTC
Labels: task:S2015R
