### ISSUE TITLE
Automated testing failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/forces-and-motion-basics#144] opened 2015-11-09 19:46 UTC
```
TypeError: Cannot read property 'zeroOnRelease' of undefined
    at Object.HSlider.SimpleDragHandler.end (http://192.168.0.2:8080/forces-and-motion-basics/js/motion/view/HSlider.js?bust=1447096483074:143:30)
    at SimpleDragHandler.inherit.endDrag (http://192.168.0.2:8080/scenery/js/input/SimpleDragHandler.js?bust=1447096483074:164:22)
    at Object.SimpleDragHandler.dragListener.up (http://192.168.0.2:8080/scenery/js/input/SimpleDragHandler.js?bust=1447096483074:74:19)
    at Input.inherit.dispatchToPointer (http://192.168.0.2:8080/scenery/js/input/Input.js?bust=1447096483074:815:29)
    at Input.inherit.dispatchEvent (http://192.168.0.2:8080/scenery/js/input/Input.js?bust=1447096483074:788:14)
    at Input.inherit.upEvent (http://192.168.0.2:8080/scenery/js/input/Input.js?bust=1447096483074:653:14)
    at Input.inherit.mouseUp (http://192.168.0.2:8080/scenery/js/input/Input.js?bust=1447096483074:325:14)
    at Display.extend.fuzzMouseEvents (http://192.168.0.2:8080/scenery/js/display/Display.js?bust=1447096483074:1062:25)
    at ForcesAndMotionBasicsSim.inherit.stepSimulation (http://192.168.0.2:8080/joist/js/Sim.js?bust=1447096483074:712:22)
    at ForcesAndMotionBasicsSim.inherit.runAnimationLoop (http://192.168.0.2:8080/joist/js/Sim.js?bust=1447096483074:687:12)
```

**Comment by jessegreenberg** [comment] 2015-11-11 01:19
Assigning to myself, likely a breaking change accidentally introduced through accessible content.

**Comment by jessegreenberg** [comment] 2015-11-12 18:26
Looks like options extension was standardized a while ago, but options scope was not properly extended.  Fixed in the commit above.  Can no longer reproduce the issue.  Sim passes through a fuzz test. Closing.

**Closed by jessegreenberg** 2015-11-12 18:26 UTC
Labels: bug
