### ISSUE TITLE
Consider a stopwatch tool

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/forces-and-motion-basics#303] opened 2023-07-31 21:58 UTC
In thinking about lessons with @matthew-blackman we thought a stopwatch tool might help for this sim - to determine acceleration on screens that don't have an acceleration tool.

**Comment by amanda-phet** [comment] 2023-12-15 19:49
This is a duplicate of https://github.com/phetsims/forces-and-motion-basics/issues/288. Closing.

**Closed by amanda-phet** 2023-12-15 19:49 UTC
Labels: design:general
